In [45]:
import numpy as np
import pandas as pd

import CoC

In [46]:
from os import listdir
from os.path import isfile, join
cl = [f for f in listdir("./database/clan") if isfile(join("./database/clan", f))]
op = [f for f in listdir("./database/opponent") if isfile(join("./database/opponent", f))]

In [47]:
cl = pd.read_pickle(f"./database/clan/{cl[0]}")
op = pd.read_pickle(f"./database/opponent/{op[0]}")

In [48]:
clan, opponent = CoC.indexFromPickle(clan=cl, opponent=op)

In [49]:
clan

,attackerTag,defenderTag,stars,destructionPercentage,order,name,townhallLevel,expLevel,trophies,troops
0,#2QVV2CGJ,#20V0Q9U92,2,83,12,Federico,13,221,5276,425
1,#2QVV2CGJ,#PQYJGJCCL,3,100,18,Federico,13,221,5276,425
2,#8LR0JGLR,#2LJY8JJ8U,3,100,17,alessandro,13,200,4740,404
3,#8U9VLVLY,#LQ980QYP,3,100,13,Il Magnifico,13,196,4500,323
4,#CJJCVJCQ,#2YYVL0QQP,3,100,15,Revenger,12,174,4055,299
5,#CJJCVJCQ,#GP9J2P00,2,99,24,Revenger,12,174,4055,299
6,#R28RQY2U,#GP9J2P00,2,92,22,Walter 007,11,165,3802,293
7,#9Q28CJY2R,#2YYVL0QQP,1,71,11,R3Di,11,132,2806,209
8,#90CQYLPJ,#GP9J2P00,2,75,1,Subliminal,11,142,2913,228
9,#90CQYLPJ,#P8LV9CR90,3,100,16,Subliminal,11,142,2913,228
10,#LR0LYLLYL,#P8LV9CR90,2,65,6,⚡️ViNcEnZo⚡️,10,97,2927,137
11,#LR0LYLLYL,#9URV9L09Y,2,68,23,⚡️ViNcEnZo⚡️,10,97,2927,137
12,#220RV9202,#9URV9L09Y,1,69,19,alessandro,9,83,2391,97
13,#220RV9202,#YPJR00UGC,3,100,26,alessandro,9,83,2391,97
14,#L9PCCU8V,#YPJR00UGC,3,100,5,Tobintax,9,96,2079,97

In [50]:
opponent

,attackerTag,defenderTag,stars,destructionPercentage,order,name,townhallLevel,expLevel,trophies,troops
0,#20V0Q9U92,#2QVV2CGJ,2,62,21,wael,13,231,5003,423
1,#20V0Q9U92,#8LR0JGLR,2,86,25,wael,13,231,5003,423
2,#2LJY8JJ8U,#CJJCVJCQ,2,82,2,Semsem,13,202,3190,333
3,#2LJY8JJ8U,#8U9VLVLY,2,80,20,Semsem,13,202,3190,333
4,#PQYJGJCCL,#9Q28CJY2R,3,100,4,amr,12,175,3718,279
5,#PQYJGJCCL,#90CQYLPJ,3,100,8,amr,12,175,3718,279
6,#QY2Y9R9J,#R28RQY2U,2,74,9,ramoooz,11,161,3683,251
7,#QY2Y9R9J,#L9PCCU8V,3,100,10,ramoooz,11,161,3683,251
8,#GP9J2P00,#CJJCVJCQ,2,65,14,Hector,11,146,3184,216
9,#P8LV9CR90,#220RV9202,3,100,3,اياد,11,121,2391,153
10,#P8LV9CR90,#LR0LYLLYL,3,100,7,اياد,11,121,2391,153

In [51]:
opponent.index = opponent.attackerTag

In [52]:
opponent

,attackerTag,defenderTag,stars,destructionPercentage,order,name,townhallLevel,expLevel,trophies,troops
attackerTag,,,,,,,,,,
#20V0Q9U92,#20V0Q9U92,#2QVV2CGJ,2,62,21,wael,13,231,5003,423
#20V0Q9U92,#20V0Q9U92,#8LR0JGLR,2,86,25,wael,13,231,5003,423
#2LJY8JJ8U,#2LJY8JJ8U,#CJJCVJCQ,2,82,2,Semsem,13,202,3190,333
#2LJY8JJ8U,#2LJY8JJ8U,#8U9VLVLY,2,80,20,Semsem,13,202,3190,333
#PQYJGJCCL,#PQYJGJCCL,#9Q28CJY2R,3,100,4,amr,12,175,3718,279
#PQYJGJCCL,#PQYJGJCCL,#90CQYLPJ,3,100,8,amr,12,175,3718,279
#QY2Y9R9J,#QY2Y9R9J,#R28RQY2U,2,74,9,ramoooz,11,161,3683,251
#QY2Y9R9J,#QY2Y9R9J,#L9PCCU8V,3,100,10,ramoooz,11,161,3683,251
#GP9J2P00,#GP9J2P00,#CJJCVJCQ,2,65,14,Hector,11,146,3184,216
#P8LV9CR90,#P8LV9CR90,#220RV9202,3,100,3,اياد,11,121,2391,153
#P8LV9CR90,#P8LV9CR90,#LR0LYLLYL,3,100,7,اياد,11,121,2391,153

In [53]:
clan.index = clan.defenderTag

In [63]:
oppo = opponent.loc[clan.index].reset_index(drop=True)
oppo.columns = [a+"oppo" for a in oppo.columns]
pd.concat([clan.reset_index(drop=True), oppo], axis=1).dropna()[[""]]

/home/giulio/prog/.virtualenv/TF2/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike
  """Entry point for launching an IPython kernel.

KeyError: "None of [Index([''], dtype='object')] are in the [columns]"

In [60]:
oppo.columns = ["oppo"+a for a in oppo.columns]

In [61]:
oppo

,oppoattackerTag,oppodefenderTag,oppostars,oppodestructionPercentage,oppoorder,opponame,oppotownhallLevel,oppoexpLevel,oppotrophies,oppotroops
0,#20V0Q9U92,#2QVV2CGJ,2.0,62.0,21.0,wael,13.0,231.0,5003.0,423.0
1,#20V0Q9U92,#8LR0JGLR,2.0,86.0,25.0,wael,13.0,231.0,5003.0,423.0
2,#PQYJGJCCL,#9Q28CJY2R,3.0,100.0,4.0,amr,12.0,175.0,3718.0,279.0
3,#PQYJGJCCL,#90CQYLPJ,3.0,100.0,8.0,amr,12.0,175.0,3718.0,279.0
4,#2LJY8JJ8U,#CJJCVJCQ,2.0,82.0,2.0,Semsem,13.0,202.0,3190.0,333.0
5,#2LJY8JJ8U,#8U9VLVLY,2.0,80.0,20.0,Semsem,13.0,202.0,3190.0,333.0
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,#GP9J2P00,#CJJCVJCQ,2.0,65.0,14.0,Hector,11.0,146.0,3184.0,216.0
9,#GP9J2P00,#CJJCVJCQ,2.0,65.0,14.0,Hector,11.0,146.0,3184.0,216.0
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,#GP9J2P00,#CJJCVJCQ,2.0,65.0,14.0,Hector,11.0,146.0,3184.0,216.0
12,#P8LV9CR90,#220RV9202,3.0,100.0,3.0,اياد,11.0,121.0,2391.0,153.0
13,#P8LV9CR90,#LR0LYLLYL,3.0,100.0,7.0,اياد,11.0,121.0,2391.0,153.0
14,#P8LV9CR90,#220RV9202,3.0,100.0,3.0,اياد,11.0,121.0,2391.0,153.0
15,#P8LV9CR90,#LR0LYLLYL,3.0,100.0,7.0,اياد,11.0,121.0,2391.0,153.0
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN